### ISSUE TITLE
This plugin seems corrupted, no commands can be found to execute.

### ISSUE THREAD

**Issue by xmbai9507** [Mara-Li/obsidian-metacopy#2]
Even in sandbox.

![Image_20230729_215311](https://github.com/Lisandra-dev/obsidian-metacopy/assets/65625632/558827e1-8df0-49cf-85dd-f0c7555bee6f)

**Comment by Lisandra-dev** [comment]
Well. You litteraly need to configure the plugin and set the metadata to allow copy…

**Comment by XMB-7** [comment]
Sorry for the potentially silly question, but I'm unsure what else needs to be configured.
I just add a key named test to have a simple test, and everything goes as what the GIF in README shows, but still no commands available...
![Image_20230730_172813](https://github.com/Lisandra-dev/obsidian-metacopy/assets/65625632/2182a605-0b58-4eac-b670-a0bd70345284)
![Image_20230730_172908](https://github.com/Lisandra-dev/obsidian-metacopy/assets/65625632/16c592a0-f431-41e1-8360-f2151a332c55)
![Image_20230730_173417](https://github.com/Lisandra-dev/obsidian-metacopy/assets/65625632/1820995b-091f-47f6-b0e0-87922d015a2a)
![Image_20230730_173446](https://github.com/Lisandra-dev/obsidian-metacopy/assets/65625632/1732d4a7-6dbb-4b36-b116-4700a14daf39)

**Comment by Lisandra-dev** [comment]
You need to have the file opened when you open the command palette

**Comment by XMB-7** [comment]
Obviously I've opened a md file, otherwise the three-dot menu won't have as many options as I've shown.

![Image_20230730_192506](https://github.com/Lisandra-dev/obsidian-metacopy/assets/65625632/f119b422-5eaf-4c32-b71a-469403f7b54a)

**Comment by Lisandra-dev** [comment]
![image](https://github.com/Lisandra-dev/obsidian-metacopy/assets/30244939/bf69285f-d9d5-406e-9c75-ff908a8d7b51)

Can you send me your data.json ? I can't reproduce in my side :/

**Comment by XMB-7** [comment]
You can just open the provided obsidian sandbox and only install your plugin to have a test without any potential plugin conflicts. Afterwards, just remove the sandbox from the vault list to delete all changes.

![Image_20230730_195941](https://github.com/Lisandra-dev/obsidian-metacopy/assets/65625632/d780c45d-0403-487a-81bf-d97ed63f1276)
![Image_20230730_200411](https://github.com/Lisandra-dev/obsidian-metacopy/assets/65625632/c5093a68-4325-441b-8282-e14897762c0c)

**Comment by Lisandra-dev** [comment]
Thank you ! I made some QOL update to fix the bug and other things. Hope you enjoy the plugin now!
